name: Test Build Plugin

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.100-preview.3.21202.5

      - name: Setup node environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install dotnet dependencies
        run: dotnet restore

      - name: Install node dependencies
        run: npm ci --no-audit --prefix ./Jellyfin.Blazor/wwwroot/

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
